version: '2'
services:
  rstudio:
    image: daex/rstudio
    build: ./rstudio 
    hostname: rstudio 
    container_name: rstudio
    volumes:
      - /etc:/opt/etc:ro
      - /home:/home
  jupyter:
    image: daex/jupyter
    build: ./jupyter 
    hostname: jupyter
    container_name: jupyter
    volumes:
      - /etc:/opt/etc:ro
      - /home:/home
  shiny:
    image: rocker/shiny
    hostname: shiny
    container_name: shiny
    volumes:
     - /data/daex/shiny/apps/:/srv/shiny-server/
     - /data/daex/shiny/logs/:/var/log/shiny-server/
  nginx:
    image: daex/nginx
    build: ./nginx
    hostname: nginx
    container_name: nginx
    depends_on:
      - jupyter
      - rstudio
      - shiny
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/daex/nginx/conf:/etc/nginx
      - /data/daex/nginx/html:/usr/share/nginx/html
      - /etc:/opt/etc:ro
